import type { Ionicons } from "@expo/vector-icons";
import type { ImageSourcePropType } from "react-native";

export type IconName = keyof typeof Ionicons.glyphMap;
export type UIIcon =
  | { kind: "icon"; name: IconName }
  | { kind: "image"; source: ImageSourcePropType; tint?: boolean };

// Replace an entry with { kind: "image", source: require('./icons/calories.png') }.
// Images retain their own colours unless tint: true is supplied.
export const uiIcons = {
  packageSizeIcon: { kind: "icon", name: "cube" } as UIIcon,
  addIcon: { kind: "icon", name: "add" } as UIIcon,
  alertCircleOutlineIcon: { kind: "icon", name: "alert-circle-outline" } as UIIcon,
  proteinIcon: { kind: "icon", name: "barbell-outline" } as UIIcon,
  barcodeIcon: { kind: "icon", name: "barcode" } as UIIcon,
  barcodeOutlineIcon: { kind: "icon", name: "barcode-outline" } as UIIcon,
  basketOutlineIcon: { kind: "icon", name: "basket-outline" } as UIIcon,
  calculatorOutlineIcon: { kind: "icon", name: "calculator-outline" } as UIIcon,
  calendarOutlineIcon: { kind: "icon", name: "calendar-outline" } as UIIcon,
  cameraIcon: { kind: "icon", name: "camera" } as UIIcon,
  cameraOutlineIcon: { kind: "icon", name: "camera-outline" } as UIIcon,
  checkboxIcon: { kind: "icon", name: "checkbox" } as UIIcon,
  checkmarkIcon: { kind: "icon", name: "checkmark" } as UIIcon,
  checkmarkCircleIcon: { kind: "icon", name: "checkmark-circle" } as UIIcon,
  checkmarkCircleOutlineIcon: { kind: "icon", name: "checkmark-circle-outline" } as UIIcon,
  checkmarkOutlineIcon: { kind: "icon", name: "checkmark-outline" } as UIIcon,
  chevronBackIcon: { kind: "icon", name: "chevron-back" } as UIIcon,
  chevronDownIcon: { kind: "icon", name: "chevron-down" } as UIIcon,
  chevronForwardIcon: { kind: "icon", name: "chevron-forward" } as UIIcon,
  chevronUpIcon: { kind: "icon", name: "chevron-up" } as UIIcon,
  closeIcon: { kind: "icon", name: "close" } as UIIcon,
  closeCircleIcon: { kind: "icon", name: "close-circle" } as UIIcon,
  cloudOfflineOutlineIcon: { kind: "icon", name: "cloud-offline-outline" } as UIIcon,
  editIcon: { kind: "icon", name: "create-outline" } as UIIcon,
  sugarsIcon: { kind: "icon", name: "cube-outline" } as UIIcon,
  documentTextOutlineIcon: { kind: "icon", name: "document-text-outline" } as UIIcon,
  ellipseOutlineIcon: { kind: "icon", name: "ellipse-outline" } as UIIcon,
  caloriesIcon: { kind: "icon", name: "flame-outline" } as UIIcon,
  saltIcon: { kind: "icon", name: "flask-outline" } as UIIcon,
  helpCircleOutlineIcon: { kind: "icon", name: "help-circle-outline" } as UIIcon,
  homeIcon: { kind: "icon", name: "home" } as UIIcon,
  placeholderIcon: { kind: "icon", name: "image-outline" } as UIIcon,
  imagesIcon: { kind: "icon", name: "images" } as UIIcon,
  informationCircleOutlineIcon: { kind: "icon", name: "information-circle-outline" } as UIIcon,
  fibreIcon: { kind: "icon", name: "leaf-outline" } as UIIcon,
  listIcon: { kind: "icon", name: "list" } as UIIcon,
  lockClosedOutlineIcon: { kind: "icon", name: "lock-closed-outline" } as UIIcon,
  logOutOutlineIcon: { kind: "icon", name: "log-out-outline" } as UIIcon,
  carbsIcon: { kind: "icon", name: "nutrition-outline" } as UIIcon,
  optionsOutlineIcon: { kind: "icon", name: "options-outline" } as UIIcon,
  pencilOutlineIcon: { kind: "icon", name: "pencil-outline" } as UIIcon,
  radioIcon: { kind: "icon", name: "radio" } as UIIcon,
  radioButtonOffIcon: { kind: "icon", name: "radio-button-off" } as UIIcon,
  radioButtonOnIcon: { kind: "icon", name: "radio-button-on" } as UIIcon,
  removeIcon: { kind: "icon", name: "remove" } as UIIcon,
  restaurantIcon: { kind: "icon", name: "restaurant" } as UIIcon,
  restaurantOutlineIcon: { kind: "icon", name: "restaurant-outline" } as UIIcon,
  searchFilledIcon: { kind: "icon", name: "search" } as UIIcon,
  searchIcon: { kind: "icon", name: "search-outline" } as UIIcon,
  settingsFilledIcon: { kind: "icon", name: "settings" } as UIIcon,
  settingsIcon: { kind: "icon", name: "settings-outline" } as UIIcon,
  shieldCheckmarkOutlineIcon: { kind: "icon", name: "shield-checkmark-outline" } as UIIcon,
  squareOutlineIcon: { kind: "icon", name: "square-outline" } as UIIcon,
  todayIcon: { kind: "icon", name: "today" } as UIIcon,
  deleteIcon: { kind: "icon", name: "trash-outline" } as UIIcon,
  walletOutlineIcon: { kind: "icon", name: "wallet-outline" } as UIIcon,
  fatIcon: { kind: "icon", name: "water-outline" } as UIIcon,
};

// Keeps existing screen icon names connected to the configurable entries.
export const iconKeys: Partial<Record<IconName, keyof typeof uiIcons>> = {
  "cube": "packageSizeIcon",
  "add": "addIcon",
  "alert-circle-outline": "alertCircleOutlineIcon",
  "barbell-outline": "proteinIcon",
  "barcode": "barcodeIcon",
  "barcode-outline": "barcodeOutlineIcon",
  "basket-outline": "basketOutlineIcon",
  "calculator-outline": "calculatorOutlineIcon",
  "calendar-outline": "calendarOutlineIcon",
  "camera": "cameraIcon",
  "camera-outline": "cameraOutlineIcon",
  "checkbox": "checkboxIcon",
  "checkmark": "checkmarkIcon",
  "checkmark-circle": "checkmarkCircleIcon",
  "checkmark-circle-outline": "checkmarkCircleOutlineIcon",
  "checkmark-outline": "checkmarkOutlineIcon",
  "chevron-back": "chevronBackIcon",
  "chevron-down": "chevronDownIcon",
  "chevron-forward": "chevronForwardIcon",
  "chevron-up": "chevronUpIcon",
  "close": "closeIcon",
  "close-circle": "closeCircleIcon",
  "cloud-offline-outline": "cloudOfflineOutlineIcon",
  "create-outline": "editIcon",
  "cube-outline": "sugarsIcon",
  "document-text-outline": "documentTextOutlineIcon",
  "ellipse-outline": "ellipseOutlineIcon",
  "flame-outline": "caloriesIcon",
  "flask-outline": "saltIcon",
  "help-circle-outline": "helpCircleOutlineIcon",
  "home": "homeIcon",
  "image-outline": "placeholderIcon",
  "images": "imagesIcon",
  "information-circle-outline": "informationCircleOutlineIcon",
  "leaf-outline": "fibreIcon",
  "list": "listIcon",
  "lock-closed-outline": "lockClosedOutlineIcon",
  "log-out-outline": "logOutOutlineIcon",
  "nutrition-outline": "carbsIcon",
  "options-outline": "optionsOutlineIcon",
  "pencil-outline": "pencilOutlineIcon",
  "radio": "radioIcon",
  "radio-button-off": "radioButtonOffIcon",
  "radio-button-on": "radioButtonOnIcon",
  "remove": "removeIcon",
  "restaurant": "restaurantIcon",
  "restaurant-outline": "restaurantOutlineIcon",
  "search": "searchFilledIcon",
  "search-outline": "searchIcon",
  "settings": "settingsFilledIcon",
  "settings-outline": "settingsIcon",
  "shield-checkmark-outline": "shieldCheckmarkOutlineIcon",
  "square-outline": "squareOutlineIcon",
  "today": "todayIcon",
  "trash-outline": "deleteIcon",
  "wallet-outline": "walletOutlineIcon",
  "water-outline": "fatIcon",
};

// Decorative images remain in their existing configuration.
export { artwork } from "./artwork";

// Native tabs accept system symbols or a local image via { src: require(...) }.
export const tabIcons = {
  home: { sf: "house.fill", md: "home" },
  pantry: { sf: "cooktop", md: "settings" },
  search: { sf: "magnifyingglass", md: "search" },
  meals: { sf: "fork.knife", md: "restaurant" },
} as const;
