const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { PGlite } = require(process.env.FOODWORTH_PGLITE_PATH || "@electric-sql/pglite");

test("public meals: copy choices, direct logging, retries, rollback, authorization", async () => {
 const db=new PGlite();
 const owner="11111111-1111-4111-8111-111111111111", other="22222222-2222-4222-8222-222222222222";
 const nutrition="calories_per_100 numeric, protein_per_100 numeric, carbs_per_100 numeric, fat_per_100 numeric, sugars_per_100 numeric, salt_per_100 numeric, fibre_per_100 numeric";
 try {
    await db.exec(`
      create role anon; create role authenticated; create schema auth;
      create table auth.users(id uuid primary key);
      create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema auth to authenticated;
      create table public.meals(id bigint generated by default as identity primary key, user_id uuid references auth.users(id), meal_name text, description text, instructions text);
      create table public.admin_users(user_id uuid primary key);
      create table public.products(barcode_number text primary key, product_name text, measurement_unit text, ${nutrition});
      create table public.generic_products(id bigint primary key, product_name text, measurement_unit text, ${nutrition});
      create table public.product_corrections(product_barcode text, user_id uuid, product_name text, measurement_unit text, ${nutrition}, primary key(product_barcode,user_id));
      create table public.meal_items(id bigint generated by default as identity primary key, meal_id bigint references public.meals(id) on delete cascade, product_barcode text, generic_product_id bigint, amount numeric(12,3));
      create table public.pantry(id bigint primary key, user_id uuid, product_barcode text, generic_product_id bigint, amount_remaining numeric(12,3) check(amount_remaining>0));
      insert into auth.users values ('${owner}'),('${other}');
      insert into public.meals(id,user_id,meal_name) values (1,'${owner}','Smoothie'),(2,'${other}','Private'),(3,'${owner}','Empty');
      insert into public.products values ('123','Milk','ml',60,3,5,3,5,0.1,0);
      insert into public.generic_products values (1,'Oats','g',400,10,60,10,5,0.1,8),(2,'Egg','g',143,12.6,null,null,null,null,null);
      insert into public.product_corrections values ('123','${owner}','My milk','ml',70,null,null,null,null,null,null);
      insert into public.meal_items values (1,1,'123',null,100),(2,1,null,1,50),(3,1,null,2,50);
      insert into public.pantry values (1,'${owner}','123',null,150),(2,'${owner}',null,1,20),(3,'${other}','123',null,500);
      select set_config('request.jwt.claim.sub','${owner}',false);
    `);
    for (const file of ["20260912_food_consumption.sql", "20260912_log_food_consumption.sql", "20260916_consumption_meal_period.sql", "20260919_public_meals.sql"])
      await db.exec(fs.readFileSync(path.join(__dirname, "../supabase/migrations", file), "utf8"));


 await db.exec(`alter sequence meals_id_seq restart with 10; alter sequence meal_items_id_seq restart with 10;
 grant select on public.admin_users to authenticated;
 insert into public.public_meals(meal_name,servings,image_path) values('Oats and milk',4,'public-meals/1/image.webp');
 insert into public.public_meal_ingredients(public_meal_id,generic_product_id,amount,measurement_unit) values(1,1,50,'g'),(1,2,100,'ml');
 update public.generic_products set measurement_unit='ml' where id=2;
`);
 const legacyGroup='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
 const legacyItems=JSON.stringify([{ingredient_id:1,generic_product_id:1,amount:25},{ingredient_id:2,product_barcode:'123',amount:50}]);
 await db.query("select * from log_public_meal(1,2,$1,$2,'2026-09-18','UTC',false,'Lunch')",[legacyItems,legacyGroup]);
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260919_public_meal_types.sql'),'utf8'));
 const replay=(await db.query("select * from log_public_meal(1,$1,$2,'2026-09-18','UTC',true,'Lunch')",[legacyItems,legacyGroup])).rows;
 assert.deepEqual(replay.map(r=>Number(r.amount_consumed)).sort((a,b)=>a-b),[25,50]);
 assert.equal(Number((await db.query('select amount_remaining from pantry where id=1')).rows[0].amount_remaining),150);
 await assert.rejects(db.exec("update public_meals set meal_type='quick Meals'"),/check constraint/);
 await db.exec("insert into public_meal_ingredients(public_meal_id,generic_product_id,amount,measurement_unit,is_optional) values(1,1,5,'g',true)");

 assert.deepEqual((await db.query('select meal_type from public_meals')).rows,[{meal_type:'Other'}]);
 assert.equal((await db.query("select * from information_schema.columns where table_name='public_meals' and column_name='servings'")).rows.length,0);
 await db.exec("update public_meals set meal_type='Budget meals' where id=1; set role authenticated");
 assert.deepEqual((await db.query('select * from public_meal_types()')).rows,[{meal_type:'Budget meals'}]);
 const choices=[{ingredient_id:1,generic_product_id:1,amount:50},{ingredient_id:2,product_barcode:'123',amount:100}];
 const save=()=>db.query('select public.save_public_meal(1,$1) id',[JSON.stringify(choices)]);
 const saved=(await save()).rows[0].id;
 await assert.rejects(db.exec("insert into public.public_meals(meal_name) values('Not admin')"),/row-level security/);
 await db.exec('reset role');
 const copy=(await db.query('select * from meals where id=$1',[saved])).rows[0];
 assert.equal(copy.public_image_path,'public-meals/1/image.webp');
 assert.equal(copy.user_id,owner);
 const items=(await db.query('select * from meal_items where meal_id=$1 order by id',[saved])).rows;
 assert.deepEqual(items.map(i=>Number(i.amount)).sort((a,b)=>a-b),[50,100]);
 assert.equal(items.length,2);assert.ok(items.some(i=>i.product_barcode==='123'));assert.ok(items.some(i=>i.generic_product_id===1));
 const trip='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
 const log=(group,items=choices,remove=true)=>db.query("select * from log_public_meal(1,$1,$2,'2026-09-18','UTC',$3,'Lunch')",[JSON.stringify(items),group,remove]);
 await db.exec('set role authenticated');
 const rows=(await log(trip)).rows;
 assert.equal(rows.length,2);assert.ok(rows.every(r=>r.meal_id===null && r.meal_name_snapshot==='Oats and milk' && r.meal_period==='Lunch'));
 assert.equal((await log(trip)).rows.length,2);
 await db.exec('reset role');
 assert.equal(Number((await db.query('select amount_remaining from pantry where id=1')).rows[0].amount_remaining),50);
 assert.equal((await db.query('select * from pantry where id=2')).rows.length,0);
 assert.equal((await db.query('select * from pantry where id=3')).rows[0].user_id,other);
 assert.equal(Number((await db.query('select count(*) n from meals')).rows[0].n),4);
 // No pantry change for unchecked logging.
 await log('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',choices,false);
 assert.equal(Number((await db.query('select amount_remaining from pantry where id=1')).rows[0].amount_remaining),50);
 // Reject missing required ingredients, wrong units, wrong recipe totals and unknown products.
 for(const invalid of [choices.slice(0,1),[{...choices[0],amount:49},choices[1]],[{...choices[0],generic_product_id:null,product_barcode:'123'},choices[1]],[choices[0],{...choices[1],product_barcode:'missing'}]]) {
   await assert.rejects(log('cccccccc-cccc-4ccc-8ccc-cccccccccccc',invalid));
 }
 // A failure in the second nested log rolls back the first deduction and snapshot.
 await db.exec("update product_corrections set calories_per_100=-1 where product_barcode='123'");
 await assert.rejects(log('dddddddd-dddd-4ddd-8ddd-dddddddddddd'));
 assert.equal((await db.query("select * from food_consumption where consumption_group_id='dddddddd-dddd-4ddd-8ddd-dddddddddddd'")).rows.length,0);
 assert.equal(Number((await db.query('select amount_remaining from pantry where id=1')).rows[0].amount_remaining),50);
 await db.exec("select set_config('request.jwt.claim.sub','',false)");
 await assert.rejects(save(),/Sign in/);
 } finally { await db.close(); }
});
