const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require(process.env.FOODWORTH_PGLITE_PATH||'@electric-sql/pglite');
test('shopping checkout is atomic, retry-safe, private and stores value snapshots',async()=>{
 const db=new PGlite();
 const owner='11111111-1111-4111-8111-111111111111', other='22222222-2222-4222-8222-222222222222';
 let sequence=0;
 const id=()=>`00000000-0000-4000-8000-${String(++sequence).padStart(12,'0')}`;
 const purchase={product_barcode:'123',generic_product_id:null,amount:500,price:1,measurement_unit:'g',brand:'Brand'};
 const checkout=(trip,items)=>db.query('select complete_shopping($1,$2)',[trip,JSON.stringify(items)]);
 try{
 await db.exec(`create role anon;create role authenticated;create schema auth;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to authenticated;
 create table products(barcode_number text primary key,product_name text,measurement_unit text,calories_per_100 numeric,protein_per_100 numeric);
 create table generic_products(id bigint primary key,product_name text,measurement_unit text,calories_per_100 numeric,protein_per_100 numeric);
 create table product_corrections(product_barcode text,user_id uuid,product_name text,measurement_unit text,calories_per_100 numeric,protein_per_100 numeric,primary key(product_barcode,user_id));
 create table user_settings(user_id uuid primary key,cost_target_per_day numeric,calories_target_per_day numeric,protein_target_per_day numeric);
 create table pantry(id bigint generated always as identity primary key,user_id uuid,product_barcode text,generic_product_id bigint,
 amount_remaining numeric(12,3) check(amount_remaining>0 and amount_remaining<=100000000),unique(user_id,product_barcode),unique(user_id,generic_product_id));
 insert into auth.users values('${owner}'),('${other}');
 insert into user_settings values('${owner}',3,3000,150);
 insert into products values('123','Oats','g',380,13);
 insert into generic_products values(1,'Milk','ml',60,3);
 insert into pantry(user_id,product_barcode,amount_remaining) values('${owner}','123',100),('${other}','123',50);
 select set_config('request.jwt.claim.sub','${owner}',false);`);
 await db.exec(fs.readFileSync('supabase/migrations/20260918_shopping.sql','utf8'));
 const first=id();
 await db.exec('set role authenticated');
 await checkout(first,[purchase,{product_barcode:null,generic_product_id:1,amount:100,price:0,measurement_unit:'ml'}]);
 let items=(await db.query('select * from shopping_trip_items order by id')).rows;
 assert.equal(items.length,2);
 assert.equal(Number(items[0].calorie_percentage),190);
 assert.equal(Number(items[0].protein_percentage),130);
 assert.equal(items[0].overall_grade,'A');assert.equal(items[0].brand_snapshot,'Brand');
 assert.equal(items[1].overall_grade,null);
 await checkout(first,[purchase]); // response lost: no duplicate stock or rows
 assert.equal((await db.query('select * from shopping_trips')).rows.length,1);
 await assert.rejects(db.query('delete from shopping_trips'),/permission denied/);
 await assert.rejects(db.query("update shopping_trip_items set price_paid=0"),/permission denied/);
 await db.exec('reset role');
 assert.deepEqual((await db.query('select amount_remaining from pantry order by id')).rows.map(r=>Number(r.amount_remaining)),[600,50,100]);
 const broken=id();
 await assert.rejects(checkout(broken,[purchase,{...purchase,product_barcode:'missing'}]),/no longer available/);
 assert.equal((await db.query('select * from shopping_trips where id=$1',[broken])).rows.length,0);
 assert.equal(Number((await db.query("select amount_remaining from pantry where user_id=$1 and product_barcode='123'",[owner])).rows[0].amount_remaining),600);
 for(const patch of [{amount:0},{price:-1},{amount:NaN},{price:1.123},{measurement_unit:'ml'},{generic_product_id:1}]){
  await assert.rejects(checkout(id(),[{...purchase,...patch}]));
 }
 await assert.rejects(checkout(id(),[{...purchase,amount:100000000}]),/check constraint/);
 await db.exec("update products set product_name='Changed',calories_per_100=1;update user_settings set cost_target_per_day=1");
 items=(await db.query('select * from shopping_trip_items order by id')).rows;
 assert.equal(items[0].product_name_snapshot,'Oats');assert.equal(items[0].overall_grade,'A');
 await db.exec(`select set_config('request.jwt.claim.sub','${other}',false);set role authenticated;`);
 assert.equal((await db.query('select * from shopping_trips')).rows.length,0);
 assert.equal((await db.query('select * from shopping_trip_items')).rows.length,0);
 await assert.rejects(checkout(first,[purchase]),/duplicate key/);
 // Unknown targets produce null grades; another user's checkout is independent.
 await checkout(id(),[purchase]);
 assert.equal((await db.query('select overall_grade from shopping_trip_items')).rows[0].overall_grade,null);
 await db.exec('reset role;set role anon');
 await assert.rejects(checkout(id(),[purchase]),/permission denied/);
 await db.exec('reset role');
 await db.exec(fs.readFileSync('supabase/migrations/20260918_delete_shopping_trip.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20260918_delete_shopping_item.sql','utf8'));
 await db.exec(`select set_config('request.jwt.claim.sub','${owner}',false)`);
 const editable=id();
 await checkout(editable,[purchase,{...purchase,price:2.25}]);
 const bought=(await db.query('select id from shopping_trip_items where shopping_trip_id=$1 order by id',[editable])).rows;
 const beforeItemDelete=(await db.query('select * from pantry order by id')).rows;
 await db.exec(`select set_config('request.jwt.claim.sub','${other}',false);set role authenticated`);
 assert.equal((await db.query('select delete_shopping_item($1,$2) as n',[editable,bought[0].id])).rows[0].n,0);
 await db.exec(`select set_config('request.jwt.claim.sub','${owner}',false)`);
 assert.equal((await db.query('select delete_shopping_item($1,$2) as n',[first,bought[0].id])).rows[0].n,0);
 assert.equal((await db.query('select delete_shopping_item($1,$2) as n',[editable,bought[0].id])).rows[0].n,1);
 assert.equal(Number((await db.query('select total_spent from shopping_trips where id=$1',[editable])).rows[0].total_spent),2.25);
 assert.equal((await db.query('select delete_shopping_item($1,$2) as n',[editable,bought[0].id])).rows[0].n,0);
 assert.equal((await db.query('select delete_shopping_item($1,$2) as n',[editable,bought[1].id])).rows[0].n,1);
 assert.equal((await db.query('select * from shopping_trips where id=$1',[editable])).rows.length,0);
 await db.exec('reset role');
 assert.deepEqual((await db.query('select * from pantry order by id')).rows,beforeItemDelete);
 await db.exec('set role anon');
 await assert.rejects(db.query('select delete_shopping_item($1,$2)',[first,bought[0].id]),/permission denied/);
 await db.exec(`reset role;select set_config('request.jwt.claim.sub','${other}',false)`);
 const stockBefore=(await db.query('select * from pantry order by id')).rows;
 await db.exec('set role authenticated');
 // Still signed in as the other user: their delete cannot touch the owner's trip.
 assert.equal((await db.query('delete from shopping_trips where id=$1 returning id',[first])).rows.length,0);
 await db.exec(`select set_config('request.jwt.claim.sub','${owner}',false)`);
 assert.equal((await db.query('delete from shopping_trips where id=$1 returning id',[first])).rows.length,1);
 assert.equal((await db.query('select * from shopping_trip_items where shopping_trip_id=$1',[first])).rows.length,0);
 assert.equal((await db.query('delete from shopping_trips where id=$1 returning id',[first])).rows.length,0);
 await db.exec('reset role');
 assert.deepEqual((await db.query('select * from pantry order by id')).rows,stockBefore);
 assert.equal((await db.query('select * from shopping_trips where user_id=$1',[other])).rows.length,1);
 await db.exec('set role anon');
 await assert.rejects(db.query('delete from shopping_trips'),/permission denied/);
 await db.exec(`reset role;select set_config('request.jwt.claim.sub','${owner}',false)`);
 await checkout(id(),[purchase]);
 await db.exec(`reset role;
 update user_settings set cost_target_per_day=1,calories_target_per_day=100,protein_target_per_day=100 where user_id='${owner}';
 update products set calories_per_100=95.9,protein_per_100=95.9 where barcode_number='123';`);
 const regradeTrip=id();
 await checkout(regradeTrip,[{...purchase,amount:100,price:1}]);
 const beforeRegrade=(await db.query('select * from shopping_trip_items where shopping_trip_id=$1',[regradeTrip])).rows[0];
 assert.equal(beforeRegrade.overall_grade,'B');
 await db.exec(fs.readFileSync('supabase/migrations/20260918_value_grade_thresholds.sql','utf8'));
 const afterRegrade=(await db.query('select * from shopping_trip_items where shopping_trip_id=$1',[regradeTrip])).rows[0];
 assert.deepEqual(afterRegrade,{...beforeRegrade,overall_grade:'A'});
 const newGradeTrip=id();
 await checkout(newGradeTrip,[{...purchase,amount:100,price:1}]);
 assert.equal((await db.query('select overall_grade from shopping_trip_items where shopping_trip_id=$1',[newGradeTrip])).rows[0].overall_grade,'A');
 await db.exec(`delete from auth.users where id='${owner}';`);
 assert.equal((await db.query('select * from shopping_trips where user_id=$1',[owner])).rows.length,0);
 assert.equal((await db.query('select * from shopping_trip_items where shopping_trip_id=$1',[first])).rows.length,0);
 }finally{await db.close();}
});
